<?php

namespace Database\Seeders;

use App\Models\Sekolah;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SekolahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Kota Parepare
            // Kecamatan Bacukiki
            [
                'nama_sekolah' => 'TK AISYIYAH 5',
                'npsn_sekolah' => '40315429',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK AL QUROBIL',
                'npsn_sekolah' => '69847315',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK AL-ISRA',
                'npsn_sekolah' => '69847316',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK D NAILAH',
                'npsn_sekolah' => '69987941',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. ADE REZKY',
                'npsn_sekolah' => '69949925',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. AIRAH FATHIN AZZAHRA',
                'npsn_sekolah' => '69980445',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. AL -I TIROOF',
                'npsn_sekolah' => '69980047',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. FADIL RAHMAT',
                'npsn_sekolah' => '69987643',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. GRAND LAUGI',
                'npsn_sekolah' => '69959148',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. PAMULANG',
                'npsn_sekolah' => '70001994',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. PELANGI HARAPAN',
                'npsn_sekolah' => '69974517',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. SAFRI ANNURSIAH',
                'npsn_sekolah' => '69979844',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS AL-AQSHA',
                'npsn_sekolah' => '40315390',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS ALTERNATIF',
                'npsn_sekolah' => '40315392',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 31 PAREPARE',
                'npsn_sekolah' => '40307765',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 32 PAREPARE',
                'npsn_sekolah' => '40307748',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 37 PAREPARE',
                'npsn_sekolah' => '40307753',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 51 PAREPARE',
                'npsn_sekolah' => '40307649',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 58 PAREPARE',
                'npsn_sekolah' => '40307656',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 76 PAREPARE',
                'npsn_sekolah' => '40307633',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 77 PAREPARE',
                'npsn_sekolah' => '40307632',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 83 PAREPARE',
                'npsn_sekolah' => '40307645',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 85 PAREPARE',
                'npsn_sekolah' => '40307643',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 89 PAREPARE',
                'npsn_sekolah' => '40307640',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 11 PAREPARE',
                'npsn_sekolah' => '40307679',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 13 PAREPARE',
                'npsn_sekolah' => '40312453',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 7 PAREPARE',
                'npsn_sekolah' => '40307686',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 8 PAREPARE',
                'npsn_sekolah' => '40307687',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMP AL BADAR BILALANG PAREPARE',
                'npsn_sekolah' => '40307688',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMP ISLAM DARU ANWAARIL FIRDAUS',
                'npsn_sekolah' => '70039960',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMK AL BADAR PAREPARE',
                'npsn_sekolah' => '40314691',
                'bp_sekolah' => 'SMK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'PKBM AL HIDAYAH',
                'npsn_sekolah' => 'P2964377',
                'bp_sekolah' => 'PKBM',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'PKBM LEMOE',
                'npsn_sekolah' => 'P2964370',
                'bp_sekolah' => 'PKBM',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'PKBM PANRITA',
                'npsn_sekolah' => 'P9999236',
                'bp_sekolah' => 'PKBM',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Bacukiki',
                'kabupaten' => 'Kota Parepare',
            ],

            // Kecamatan Ujung
            [
                'nama_sekolah' => 'TK. BANDAR MADANI',
                'npsn_sekolah' => '40315413',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK.NURHALIFAH',
                'npsn_sekolah' => '69918390',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'PAUD TERPADU AL-MADINAH',
                'npsn_sekolah' => '70008902',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK AZ ZAITUN',
                'npsn_sekolah' => '40315409',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK MELATI',
                'npsn_sekolah' => '69900215',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK PGRI UJUNG',
                'npsn_sekolah' => '40315406',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK SYAHRAH',
                'npsn_sekolah' => '40315407',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. ADHYAKSA DHARMAKARINI',
                'npsn_sekolah' => '70001999',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. AMANDA',
                'npsn_sekolah' => '40315411',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. ANUGRAH',
                'npsn_sekolah' => '40315410',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. KARTIKA XX-40',
                'npsn_sekolah' => '40315405',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TK. TAHFIZH AL ILMI',
                'npsn_sekolah' => '69988603',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKIT DARUL QURAN MADANI PAREPARE',
                'npsn_sekolah' => '70027759',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKIT. ANDALUSIA',
                'npsn_sekolah' => '69980574',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS AISYIYAH 2',
                'npsn_sekolah' => '40315426',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS HIGSDI',
                'npsn_sekolah' => '40315408',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS KARTIKA XX 39',
                'npsn_sekolah' => '40315402',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS KATOLIK',
                'npsn_sekolah' => '40315403',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'TKS NURUL HUDA',
                'npsn_sekolah' => '40315404',
                'bp_sekolah' => 'TK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'KB. KARTIKA TATAG CENDEKIA',
                'npsn_sekolah' => '69927081',
                'bp_sekolah' => 'KB',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 1 PAREPARE',
                'npsn_sekolah' => '40307724',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 11 PAREPARE',
                'npsn_sekolah' => '40307745',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 17 PAREPARE',
                'npsn_sekolah' => '40307781',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 18 PAREPARE',
                'npsn_sekolah' => '40307780',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 20 PAREPARE',
                'npsn_sekolah' => '40307767',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 21 PAREPARE',
                'npsn_sekolah' => '40307785',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 22 PAREPARE',
                'npsn_sekolah' => '40307786',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 29 PAREPARE',
                'npsn_sekolah' => '40307788',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 3 PAREPARE',
                'npsn_sekolah' => '40307787',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 30 PAREPARE',
                'npsn_sekolah' => '40307766',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 4 PAREPARE',
                'npsn_sekolah' => '40307756',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 44 PAREPARE',
                'npsn_sekolah' => '40307759',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 48 PAREPARE',
                'npsn_sekolah' => '40307763',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 49 PAREPARE',
                'npsn_sekolah' => '40307764',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 5 PAREPARE',
                'npsn_sekolah' => '40307747',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 55 PAREPARE',
                'npsn_sekolah' => '40307653',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 61 PAREPARE',
                'npsn_sekolah' => '40307658',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 62 PAREPARE',
                'npsn_sekolah' => '40307659',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 86 PAREPARE',
                'npsn_sekolah' => '40307642',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SD NEGERI 9 PAREPARE',
                'npsn_sekolah' => '40307639',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SD KATOLIK PAREPARE',
                'npsn_sekolah' => '40307714',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SD MUHAMMADIYAH 2 PAREPARE',
                'npsn_sekolah' => '40307719',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SD MUHAMMADIYAH 3 PAREPARE',
                'npsn_sekolah' => '40307720',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 1 PAREPARE',
                'npsn_sekolah' => '40307676',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 10 PAREPARE',
                'npsn_sekolah' => '40307677',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 4 PAREPARE',
                'npsn_sekolah' => '40307683',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMP FRATER PAREPARE',
                'npsn_sekolah' => '40307670',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMP PGRI 1 PAREPARE',
                'npsn_sekolah' => '40307674',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMA NEGERI 1 PAREPARE',
                'npsn_sekolah' => '40307693',
                'bp_sekolah' => 'SMA',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMA NEGERI 4 PAREPARE',
                'npsn_sekolah' => '40307696',
                'bp_sekolah' => 'SMA',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMA PGRI 1 PAREPARE',
                'npsn_sekolah' => '40307692',
                'bp_sekolah' => 'SMA',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMK NEGERI 3 PAREPARE',
                'npsn_sekolah' => '40307698',
                'bp_sekolah' => 'SMK',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMK BAHARI PAREPARE',
                'npsn_sekolah' => '40307706',
                'bp_sekolah' => 'SMK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'SMK KESEHATAN BAHARI',
                'npsn_sekolah' => '69767579',
                'bp_sekolah' => 'SMK',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],
            [
                'nama_sekolah' => 'PKBM LAPADDE',
                'npsn_sekolah' => 'P2964372',
                'bp_sekolah' => 'PKBM',
                'status_sekolah' => 'Swasta',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
            ],



        ];

        // foreach ($data as $key => $v) {
        //     Sekolah::create([
        //         'nama_sekolah' => $v['nama_sekolah'],
        //         'npsn_sekolah' => $v['npsn_sekolah'],
        //         'bp_sekolah' => $v['bp_sekolah'],
        //         'status_sekolah' => $v['status_sekolah'],
        //         'kecamatan' => $v['kecamatan'],
        //         'kabupaten' => $v['kabupaten'],
        //     ]);
        // }

    }
}
